### ISSUE TITLE
[Genesis Plus GX core only] Garbage in the extension filter in the Load Game dialog

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#1]
_From @JuliaWolska on February 24, 2018 17:22_

Can't diplay "Supported Files" while browsing ROMs to load, and the menu shows weird corrupted format as an option. Games are loading correctly while displaying "All Games"
![genplusgx](https://user-images.githubusercontent.com/35509989/36633092-7494f6f4-198f-11e8-8ba2-8b006eb10b83.png)

_Copied from original issue: meleu/RALibretro#12_

**Comment by meleu** [comment]
I confirm this issue.

**Comment by meleu** [comment]
_From @leiradel on February 25, 2018 12:51_

I don't know why there's a corrupted file filter in the dialog, but the issue about not being able to load content with the Genesis supported formats was fixed here: https://github.com/leiradel/RASuite/commit/f3d57dafd39523d03e81593ac256abc43aad3ce5

**Comment by meleu** [comment]
On my tests last night I was perfectly able to load content with Genesis GX Plus, but I had to choose "All files" (and not only "Supported Files").

**Comment by leiradel** [comment]
@JuliaWolska does this still happen?

**Comment by JuliaWolska** [comment]
It's completely resolved in my opinion
