### ISSUE TITLE
Add Beetle Cygne to RALibretro

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RALibretro#120]
Tested a couple games, the Beetle Cygne core for WonderSwan/WonderSwan Color seems to be working in RALibretro

**Comment by rzumer** [comment]
This should stay opened until changes are merged.

**Comment by televandalist** [comment]
My initial post was based only testing a couple games. I've tested several more since then. Aside from the bad audio, I haven't had any issues. Finding addresses needed to make some basic cheevos has been painless. 

WonderSwan: 
Buffers Evolution
Crazy Climber (needs screen rotation)
Kaze no Klonoa: Midnight Museum
Makaimura
Rockman & Forte - Mirai Kara no Chousensha

WonderSwan Color:
Blue Wing Blitz
Dicing Knight.
Final Fantasy IV
Gunpey EX (needs screen rotation)
Judgement Silversword (needs screen rotation)
Makai Toushi Sa-Ga
Mr. Driller
Rockman EXE WS
Wizardry Scenario 1 - Proving Grounds of the Mad Overlord

**Comment by Jamiras** [comment]
implemented in #122, #123, and #124
