### ISSUE TITLE
Save States: Disable generating PNG and RAP files automatically

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RALibretro#125]
When saving a save-state on RALibreto the program create a PNG and also a RAP file from the save-state, would be useful if you can disable that, RALibretro just need the .state file to load the state not the other two files

Get very tidious while navigating through all the save states if you have a bunch and also this has happened to me a lot of times but I open the PNG file instead of the save-state file...

**Comment by eldexterr** [comment]
Or remove that behaviour entirely

**Comment by leiradel** [comment]
The PNG fixes [this bug](https://github.com/RetroAchievements/RALibretro/issues/9).
I don't know about RAP files, but games with save ram also save a `.sram` file with its contents, since they should be preserved across plays.

**Comment by eldexterr** [comment]
Oh I didn't knew was because a bug, I think I will just keep deleting those files every time RALibreto generate it

**Comment by Jamiras** [comment]
RAP files are used to persist hits when restoring a save state. While not particularly necessary when developing, they are vitally important to player who choose to play in non-hardcore mode.
