### ISSUE TITLE
Vertical Mode Does Not Work on FinalBurn Neo

### ISSUE THREAD

**Issue by jcarloslb** [RetroAchievements/RALibretro#131]
I was trying to play Donkey Kong from Arcade with the intention of seeing if there was a possibility to create achievements for this game. When I opened the game, the screen went horizontal, checked the Core settings and realized that there was an option to leave in vertical mode, but when changing the option nothing happens. The screen remains horizontal.

![01](https://user-images.githubusercontent.com/32245924/68070763-544cac00-fd51-11e9-8ccf-fbff33936b77.png)
![02](https://user-images.githubusercontent.com/32245924/68070764-544cac00-fd51-11e9-95b3-e021ce55a91b.png)

Need to do something else in the settings to rotate the screen, or is this an error in RALibretro?

**Comment by televandalist** [comment]
This is the bane of my existence. Arcade is hit the hardest by this. WonderSwan will have a few games affected by it. 

Works fine with Lynx, though.

**Comment by televandalist** [comment]
By the way, there's an issue already open for this: https://github.com/RetroAchievements/RALibretro/issues/48

**Comment by jcarloslb** [comment]
I searched but did not find, then opened a new one. I'm sorry for this.

**Comment by Jamiras** [comment]
I'm not sure what the "Vertical Mode" core setting is supposed to do, but the core does indicate that the screen should be rotated and we're just ignoring that because of #48.
