### ISSUE TITLE
Crash when clicking on "No Systems Found" in "Select Core"

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#140]
When no core is installed, there is a "No Systems Found" entry that crashes RALR for me when clicked.

I suggest greying out the entry or making it launch the core downloader window.

**Comment by Jamiras** [comment]
I get an "unable to load XXX core" error. The crash only occurs when the `cores.json` file doesn't exist.

I've added a error message when `cores.json` cannot be found, and changed the behavior of the "No Systems Found" entry to redirect to the Manage Cores window.
