### ISSUE TITLE
Modernize the file picker

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#141]
Navigating directories when looking for a file to load gets quite tedious because, short of entering the full path in the "File name" field, it is not possible to type directory names with auto-completion, use 
the "Quick access" menu, or access common directories quickly, as in most modern Windows-native applications. In Windows 10 I would like the file picker to look like the following screenshot.

![image](https://user-images.githubusercontent.com/7488362/69497526-00df0100-0eac-11ea-99e7-705c5f649fcc.png)

**Comment by rzumer** [comment]
Strangely enough, after dragging and dropping a file from Windows Explorer to RALR (which does nothing as far as I know), then clicking Load File, I get the modern file picker dialog. Closing that window and selecting Load File again reverts to the old style one.

**Comment by Jamiras** [comment]
I have seen this behavior in the past, and couldn't come up with a reliable way to reproduce it to debug it. We're just calling the `GetOpenFileName` Windows API.

After careful examination, the only explanation I can come up with if that we're initializing the `OPENFILENAME` structure one field at a time, and there's a couple fields we're not initializing. I suspect that whatever random memory is in those uninitialized fields is causing the dialog to sometimes show the old style.

**Comment by Jamiras** [comment]
I haven't seen the old-style dialog in over a month. I'm going to assume this has been fixed.
