### ISSUE TITLE
Implement Video::showMessage

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RALibretro#152]
There currently isn't any way to display on-screen text notifications for things like "Saved Slot 1" (see also #2). The intent is that functions wishing to show on-screen text would call `Video::showMessage`, but it currently just logs the message and doesn't attempt to do anything with the screen.

I tried to implement this myself several months ago using the recommended OpenGL solution of generating a texture with all valid characters and mapping them onto the surface. I was unable to get it working.

**Comment by innovation2013** [comment]
Maybe using imgui is a good solution?

**Comment by leiradel** [comment]
I believe GDI+ can be used to render a complete message to a bitmap, which can be used to create a texture to be presented on the screen. It's slower than caching individual glyphs in an atlas, but should be ok for presenting OSD messages.

There's also [stb_truetype.h](https://github.com/nothings/stb/blob/master/stb_truetype.h). which looks easier to use than GDI+.
