### ISSUE TITLE
DeSmuME core crashes when closing the lid

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#153]
As reported by a few people. It's bound to L2.

**Comment by Jamiras** [comment]
I am unable to reproduce a crash, but I can usually get it stuck in an infinite loop. I'm going to assume that's the issue that needs fixed.

**Comment by rzumer** [comment]
Seems right, the fact that closing the lid doesn't seem to do anything except turn the screen white (depending on the title?) for a split second is also an issue, but maybe separate, hanging is more critical.
