### ISSUE TITLE
PS1 Input Devices Missing from Core Settings

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RALibretro#158]
I was unable to get the analog sticks to work in Ape Escape (PlayStation), despite being able to map them. If you're unfamiliar with the game, it was the first (and I think only?) PS1 game that 100% _required_ the use of an Analog or DualShock controller. If one or the other isn't in use, then you'll get a warning screen before the game's intro movie.

I found that the end of "mednafen_psx_libretro.json"  has the following config text: `"input":[{"port":1,"device":1},{"port":2,"device":1},{"port":3,"device":1},{"port":4,"device":1},{"port":5,"device":1},{"port":6,"device":1},{"port":7,"device":1},{"port":8,"device":1}],` - yet the option to select device is not in the core settings.

KickMeElmo tested in RetroArch and found that the input devices get changed to "517"  when set as DualShock and "261" when set as Analog Controller - I tried changing the device configs above to each, but had no luck getting it to work.

**Comment by Jamiras** [comment]
#113 was tested using Ape Escape. It was working at that point. It looks like the "Controller 1"/"Controller 2" options are no longer appearing.

**Comment by televandalist** [comment]
Well I'll be a monkey's uncle...
