### ISSUE TITLE
PS1 Load Game freeze

### ISSUE THREAD

**Issue by max2188** [RetroAchievements/RALibretro#161]
Hello, I would like to create achievements for ps1, but the emulator freezes every time I try to run any rom, I have the bios in the system folder, and yet the error persists.
Here's a video I recorded from the error (ignores the quality of the video)
https://youtu.be/21utlUSL_OE

**Comment by Jamiras** [comment]
It's hard to tell what's happening from the video. Can you repeat and upload the `log.txt` and `RACache\RALog.txt` files?
