### ISSUE TITLE
Only one unknown system can be displayed at a time.

### ISSUE THREAD

**Issue by Sanaki** [RetroAchievements/RALibretro#170]
Unknown systems display in the system list as `?`, but if you have multiple unknown systems only one will be shown. In my case, I had FreeIntV (Intellivision) and P-UAE (Amiga) both added. FreeIntV was the only core displayed in the core updater's `?` section, and P-UAE was the only core displayed in the load core menu's `?` section.

**Comment by Jamiras** [comment]
Possibly expected behavior. New system support is meant to require code changes to ensure proper hashing and memory maps are set up.

**Comment by Jamiras** [comment]
Handled in #179 - system names now come from rcheevos, which supplies labels for all systems.
