### ISSUE TITLE
GBA core is missing some memory in Integration.

### ISSUE THREAD

**Issue by GameDragon2k** [RetroAchievements/RALibretro#19]
I took a quick glance and I noticed that there are two sets of memory ranges being installed in the same bank with `RA_InstallMemoryBank`. These should be installed in separate banks.

https://github.com/RetroAchievements/RALibretro/blob/972e0e783ef5b4f1b0ae4dd56d4059b1b7b77985/src/Application.cpp#L775-L791

**Comment by leiradel** [comment]
Should WRAM be bank 0 and IRAM bank 1 or the other way around?

**Comment by GameDragon2k** [comment]
Other way around. IRAM first, then WRAM.

**Comment by leiradel** [comment]
Fixed in 1.0.5
