### ISSUE TITLE
[Feature Request] CHD support

### ISSUE THREAD

**Issue by Sanaki** [RetroAchievements/RALibretro#196]
Rationale should be pretty well understood at this point. Didn't realize this one didn't have an issue filed. Would be notably beneficial for both RALibretro and RAHasher.
Library source: https://github.com/rtissera/libchdr

If anyone is unclear on why this is desirable, I'm happy to elaborate.

**Comment by Deide** [comment]
Retroarch supports this, so it would be particularly handy.

**Comment by RandomNinjaAtk** [comment]
This would be really helpful for validating a game for RA compatibility

**Comment by televandalist** [comment]
This is quickly becoming one of my most wanted features. Being able to get correct RA Hashes and dev in the PCSX2 standalone using CHDs may have spoiled me a bit.

We currently support achievements for PC Engine CD, PlayStation, Sega CD, Saturn, Dreamcast, 3DO, and PC-FX, whose cores all support CHD.
