### ISSUE TITLE
Display of action related to hotkeys

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#2]
_From @JuliaWolska on February 24, 2018 17:35_

It's less confusing to see which state is active, which was loaded or saved, and when you activate slowdown etc.
The message could be displayed in upper left corner not to get in the way of the RA overlay.

_Copied from original issue: meleu/RALibretro#14_

**Comment by Jamiras** [comment]
Conceptually, these just need to call `Video::showMessage`, but that's not implemented. I've created #152 to track that.
