### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by RobLoach** [RetroAchievements/RALibretro#22]
Could this work on Linux? Getting missing file wtypes.h .

**Comment by meleu** [comment]
Did you mean for cross compiling?

**Comment by RobLoach** [comment]
Well, I'm on Linux, trying to build/run it on Linux.

**Comment by meleu** [comment]
eh... just FYI, talking about cross-compiling again...

I've just submitted the PR #23 changing the Makefile a little bit, and I am able to cross-compile RALibretro on Linux. But unfortunately I'm having a problem (described on the PR) to launch it after cross-compiled.

**Comment by meleu** [comment]
closing this issue for now, but still have this have this as a personal dream (Linux port).

:penguin:

**Comment by BondarenkoArtur** [comment]
I'm sorry, but is the problem more than in UI ?
And how much effort might take creating Linux port?
