### ISSUE TITLE
HotKeys for Soft reset and Hard reset

### ISSUE THREAD

**Issue by Xanders08** [RetroAchievements/RALibretro#230]
Need this additional function, because if you earning achievement, in whose need reset game after fail, you need manually enter in menu and reset, but with HotKey reset will be faster and comfortable

**Comment by Jamiras** [comment]
There is no "hard reset" in the menu. I associate that with power-cycling the system, and the only real equivalency is to reload the game. That would go through the game identification process and reload the achievements from the server. I don't believe there's any achievements that require a hard reset to reattempt, so I don't see it as something that the user would want to do frequently enough to have its own hotkey.
