### ISSUE TITLE
Issue with N64 input/controller direction buttons 

### ISSUE THREAD

**Issue by Altomar79** [RetroAchievements/RALibretro#232]
I tried three games on N64 (both cores) and i have the same issue with all. The characters with all three games behave like the down direction button is stuck. 

   In Legend of Zelda - Ocarina of Time i can't use any direction button even on main menu and when the game start the character is uncontrollable and move like the down button is stuck. Every other button seems to work fine but not the direction buttons.

   In Shadowman i can use the direction buttons in the main menu but when the game start the character start moving back and i have no control on him same way like in OOT.

   In Indiana Jones sometimes the character behave like the right direction button is stuck and  just rotate around himself while some other times the character move back like with the other games. 

  This happen only with N64. I never had anything similar with the other emulators in RALibretro. (v1.3.2 and v1.3.3)
I tried to rebind other keys instead of the arrow buttons but nothing changed.

I also want to mention that i have installed the Nefarius ScpToolkit that allow you to use on win7 the PS2/3 controllers. I am not sure if N64 can mess with these drivers but other emulators like ps1 work without any problem. 

[log.txt](https://github.com/RetroAchievements/RALibretro/files/5221531/log.txt)

**Comment by Jamiras** [comment]
All joystick interactions are handled through the SDL library. I don't know how that interacts with the drivers or whatever that toolkit is that you mentioned.

When SDL tells us that an input event occurs, we look at the bindings to change that into a behavior. As far as I know, no one else has reported a similar issue yet, but the N64 core support is still fairly new.

Are you referring to the C buttons as the direction buttons? or the D-pad? Could you attach your `RALibretro.json` file (which is where the mappings are stored)?

**Comment by Altomar79** [comment]
The key binds are the same for all emulators in RALibretro. I mean the ones mentioned as up,down,left,right in the controller configuration. 
![key binds](https://user-images.githubusercontent.com/36702297/93150392-aa280980-f701-11ea-9439-a81effade353.jpg)

Here is my json. I had to zip it because GitHub wont let me upload it here.
[RALibretro.zip](https://github.com/RetroAchievements/RALibretro/files/5221709/RALibretro.zip)

Also this is the link of the drivers i mentioned here on github in case everything happen because of those,
https://github.com/nefarius/ScpToolkit

**Comment by Jamiras** [comment]
The main menu for Ocarina of Time requires the left analog stick to navigate. From your screenshot, and json file, you don't have anything mapped to Left Analog X/Y. The Up/Down/Left/Right buttons are for the d-pad. The basic PSX controller only has a d-pad. You need a Dual Shock to get analog support, and very few games require that.

Unfortunately, due to the analog nature of the analog stick (you can push it a little to walk or a lot to run), there's no way to support it via keyboard.

Is there some reason you're still using keyboard mappings in the controller configuration dialog? If ScpToolkit is doing its job, the  PS3 controller should register as an actual controller.

**Comment by Altomar79** [comment]
So this was my problem. That i used keyboard for N64 on RALibretro. When i connected my ps3 dualoshock3 controller and rebind every key the problem solved. 

I wasn't aware that most people use controllers on RA to play even for developing. I use keyboard for every emulators except the pcsx2 which was hard to use the keyboard for left and right analog as you mention. 

I guess this solved my problem. I just cant use keyboard for N64 on RALIbretro 
Thanks

**Comment by Jamiras** [comment]
I suspect that the majority of N64 games rely on the analog stick so I'm not sure if it would even be worth it, but you could leave everything else mapped to the keyboard and only map the analog sticks to the controller.

As you claim the issue has been resolved, I'm going to close this.

**Comment by Altomar79** [comment]
I tried that with ocarina but it looks like that the character movement can only be done with analog. Too bad we cant have something similar to RAP64 for digital pad. I used the numerical keyboard for analog there.
