### ISSUE TITLE
[Feature Request] libchdr shared library support in RAHasher

### ISSUE THREAD

**Issue by Sanaki** [RetroAchievements/RALibretro#240]
I understand not wanting to build external libraries into RAHasher to keep it lightweight, but would it be possible to simply support chd via the shared library? This would allow users who want chd support to build it without making a mess of the nice lightweight binary.

**Comment by Jamiras** [comment]
I have no idea what size the libchdr library is, but the plan was to add support to both RALibretro and RAHasher via #196. I'm not really concerned about size, but could add a compile flag to exclude it. Mostly, it's just not a priority for me right now.

**Comment by Sanaki** [comment]
Ah, fair enough. I thought the concern was keeping RAHasher lean. I'll close this one then.
