### ISSUE TITLE
Issue with mouse on NDS emulation

### ISSUE THREAD

**Issue by HolyShinx** [RetroAchievements/RALibretro#244]
Mouse, when playing in any size that isn't in "Window Size"  on Nintendo DS, isn't synced with your PC mouse, which is worst for games relying on touch screen, that issue is for touch pointer type, also for pointer type "mouse" the sensitivity is linked to window size.

**Comment by Jamiras** [comment]
"mouse" pointer type is meant for system that don't have a native mouse where you can move the cursor with something like a thumbstick. "touch" pointer type is preferred when the system has a way for touching a specific part of the screen (such as with a mouse cursor).

You get the same behavior in RetroArch.

**Comment by HolyShinx** [comment]
the issue is that the mouse ingame is relative to window size, not the game size, meaning positions for both settings get affected by the "black bars"

**Comment by Jamiras** [comment]
I have no problem using "Screen Gap" at 2x size, or even some custom size in "touch" mode:

![image](https://user-images.githubusercontent.com/32680403/99191578-ae38cd80-272a-11eb-9952-58fc240f99ed.png)

**Comment by HolyShinx** [comment]
I think the issue isn't there, because you didn't select "preserve aspect ratio"

**Comment by Jamiras** [comment]
And you never said "preserve aspect ratio" was a requirement to reproduce the problem. I see the issue now.

The absolute coordinates are being calculated from the size of the window, not the size of the image being rendered in the window. Black bars _within_ the image are handled appropriately. Black bars _outside_ the image cause the cursor location to be translated from the area including the external black bars.
