### ISSUE TITLE
[feature request] new-version checker

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#25]
Once we define a good way to release a zip with all needed files to run RALibretro and stop using dropbox, we can create a way to make RALibretro check if there's a new version available.

In the future we can think about auto-updating, but at first just a "new version checker" should be enough.

*suggested by @maguslogs*

**Comment by GameDragon2k** [comment]
This feature is actually already built in the the integration. The server stored version just needs to be updated to the latest.

![image](https://user-images.githubusercontent.com/3225327/39705142-85da19b0-51db-11e8-86f2-26182b966278.png)

**Comment by meleu** [comment]
@GameDragon2k can you show me where in RAIntegration's code this checking happens?

**Comment by GameDragon2k** [comment]
https://github.com/RetroAchievements/RAIntegration/blob/36679c1cc4742790e70031dc96f5f421b86c66db/src/RA_Core.cpp#L824-L868

**Comment by leiradel** [comment]
It seems to work only with versions following this pattern: `0\.[0-9]+`. RALibretro uses [Semantic Versioning](https://semver.org/).

**Comment by GameDragon2k** [comment]
There's no reason this can't be changed. The point I was making is that the feature already exists.

It just needs to be tailored for RALibretro.

**Comment by leiradel** [comment]
Sure, I'm not against the idea, just pointing out that something will have to adapt.

**Comment by meleu** [comment]
This is in fact something to be solved in RAIntegration. Opened an issue for it on that repo: RetroAchievements/RAIntegration#123.
Closing this one.
