### ISSUE TITLE
[feature request] more slots for load/save states

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#26]
Achievement developers use a bunch of savestates to check/compare the RAM behavior. It would be useful if RALibretro provided more slots for states.

It was mentioned on our discord that RAMeka has 99 slots. RALibretro could do the same. But to avoid confusion maybe it's better to wait for the implementation of what is being requested on #2.

(obviously the F1... F10 shortcuts would deal with only first ten slots, the other ones would be accessible by using the "next slot" function)

**Comment by meleu** [comment]
**ignore this comment here**
I'm just testing the rasuite-log channel on our discord...

**Comment by meleu** [comment]
**ignore this comment here**
I'm just testing the rasuite-log channel on our discord...

**Comment by leiradel** [comment]
This is in addition to loading/saving states to arbitrary files, right? I think it will only work when we have OSD messages.
