### ISSUE TITLE
Request: OSMC integration

### ISSUE THREAD

**Issue by iosoft** [RetroAchievements/RALibretro#260]
Friends,

I am using OSMC on my Raspberry Pi.
I also installed and play some NES and SNES games in it.

Pls integrate RetroAchievements with OSMC.

It will be awesome.

**Comment by Sanaki** [comment]
This repo is specifically for the RALibretro achievement dev frontend for Windows.

**Comment by Keltron3030** [comment]
Just to give some direction to the OP; if you can get Retroarch working on OSMC then you can likely earn achievements.  That would be the avenue to pursue.
