### ISSUE TITLE
[Suggestion] Keep Video settings between cores

### ISSUE THREAD

**Issue by blueYOSHI9000** [RetroAchievements/RALibretro#266]
It's annoying having to re-select 'Keep Aspect ratio' each time a new core (or console?) is selected.

**Comment by Jamiras** [comment]
Video settings are currently stored per core, whereas input bindings and saving settings are currently global. As the Video menu appears to be global, I think it would make sense to also have the video settings be global as well.

Linear filtering might make sense to enable on lower-resolution cores and disable on higher-resolution cores, but I think it's fine to remember it globally and require the user change it if desirable as they switch between systems.

The rotation setting currently isn't saved, and as far as I'm aware is only needed on some DS games that run in "book" mode. To best support that, they should be per-game settings, not even per-core. In any case, it's not currently saved anywhere.
