### ISSUE TITLE
Emulation settings: dip switch option [FBA core only]

### ISSUE THREAD

**Issue by JuliaSalsa** [RetroAchievements/RALibretro#28]
As you can see it doesn't work.
![dipswitch](https://user-images.githubusercontent.com/35509989/40379024-64a0bee0-5df5-11e8-96e4-38b9dbcd30ef.png)

**Comment by leiradel** [comment]
Does it work in RetroArch?

**Comment by JuliaWolska** [comment]
I have no idea. I will check.

**Comment by JuliaWolska** [comment]
Yeah. It works there.

**Comment by leiradel** [comment]
I think dip switches aren't in the memory address space. I'll check with the FBAlpha maintainer how I can save and restore their settings.

**Comment by Jamiras** [comment]
This appears to be working with FBNeo. I was able to change the "Free Play" option in the Core Settings dialog for Knights of the Round, and it was immediately reflected in the game after closing the dialog:
![image](https://user-images.githubusercontent.com/32680403/84572515-b5147c00-ad57-11ea-837b-0567f9e66b1a.png)
