### ISSUE TITLE
Hardcore has no System pause

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#29]
A way to pause while playing in hardcore is needed, especially for any arcade game, as there is no built in pause.

**Comment by leiradel** [comment]
I thought it was by design? Do the other emulators pause when in hardcore mode?

**Comment by meleu** [comment]
yes, RetroArch does it when you invoke the menu.

RALibretro should block the pause with `p` shortcut, but not with the `Esc` key, which is used to see the overlay. By the way, the current behavior doesn't permit users to see the overlay (and see the achievements descriptions) when playing on hardcore.

**Comment by leiradel** [comment]
> RALibretro should block the pause with p shortcut, but not with the Esc key, which is used to see the overlay.

It already works like this.
