### ISSUE TITLE
Option to hide 'Performance Problem Detected' permanently (or for current session)

### ISSUE THREAD

**Issue by blueYOSHI9000** [RetroAchievements/RALibretro#292]
It'd be nice there was a way to disable the 'Performance Problem Detected' message permanently or at least for the current session (like a 'Don't show this again' checkbox). Usually when I get that I still have to find the nearest saveblock in order to try and change options and having to dismiss the message every two second can be annoying.

**Comment by Jamiras** [comment]
Just disable hardcore until you have the settings the way you want, or switch to RetroArch.

The purpose of the feature is to prevent people with poor computers (or who have cranked up their settings) from being able to play in slow-motion.

**Comment by blueYOSHI9000** [comment]
> The purpose of the feature is to prevent people with poor computers (or who have cranked up their settings) from being able to play in slow-motion.

That makes a lot of sense actually! Though in that case, could the actual pause menu be brought up with the cheevo list? Currently it simply pauses the game (like with frame-advance) where you're able to see the full game completely paused which could give an unfair advantage there.

**Comment by Jamiras** [comment]
The overlay could be shown, but it's a lot easier to just open the File menu to pause the game with full visibility than to try to get the performance warning dialog to appear at a specific time. And even if the overlay was shown, it's semi-transparent so the screen would be mostly visible behind it anyway.

**Comment by blueYOSHI9000** [comment]
That makes sense so I'll close the issue now since none of this needs to be changed in any way. Thank you for the quick responses!
