### ISSUE TITLE
NES hash library cleanup

### ISSUE THREAD

**Issue by wholee** [RetroAchievements/RALibretro#293]
Hi,

would there be any interest in cleaning up the NES HASH library? There are numerous v14- hashes still present and I'm going through the list marking them. I used an old version of RALibRetro to verify v14- hashes because I couldn't find RAHasher that supports v14 hashes.
If there is an interest in the cleanup, I am more than happy to go through the entire list and report back to this thread.

consoleID | consoleName | ID | gameTitle | retroHash-OnLine | forumTopicID | MD5 | v14- (Taken from RaLibretro - 1.0) | v15+ | Title
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 | NES | 1525 | Adventure Island III | 5B952AF83D8865DDBF91F3E7460380A2 | 572 | 34DA8A3C0400182DE7CB96688A840A54 | 5b952af83d8865ddbf91f3e7460380a2 | 2125B772D4233E8729EDE09C0A4762F7 | Adventure Island III (U) [T+Rus_Mario Soft].nes
7 | NES | 1525 | Adventure Island III | 96A1B7B680205098C6676FAFC6B2C747 | 572 | 6A8BA7856CA6313E3FB202695B0A43FF | 96a1b7b680205098c6676fafc6b2c747 | 711DF3E4E198932E3FA869DE0E99508E | Adventure Island III (U) [T+Chi].nes
7 | NES | 1525 | Adventure Island III | EC84AC0607B01211F7EB05A670164850 | 572 | 3F8FE669D21DFEF51F16AE29D45BCF3C | ec84ac0607b01211f7eb05a670164850 | A668C20AC92FC17CD9FA91CB1BB03A3F | Adventure Island III (U) [T+Spa100%_PaladinKnights].nes
7 | NES | 1527 | Adventures in the Magic Kingdom | 20E917F703DC23C990ED2AD518424EED | 2283 | B0F8CE7BD55487614203505C20638706 | 20e917f703dc23c990ed2ad518424eed | 5219C4F1626B58BE216A6249C12FF987 | Adventures in the Magic Kingdom (E) [T+Rus_Chief-Net].nes
7 | NES | 1532 | Adventures of Lolo III | 3A908031AA0E30B2122E9468B96EAD85 | 2919 | REMOVE. V15 present | &nbsp; | &nbsp; | &nbsp;
7 | NES | 1532 | Adventures of Lolo III | A58EAC056A003F352BC9FB01248520CF | 2919 | REMOVE. V15 present | &nbsp; | &nbsp; | &nbsp;
7 | NES | 4094 | Antarctic Adventure | BBD477B940C2AAF1633294CBA9C3454D | 1694 | A49BBC7F42795CF170DAD1EB72ECEA56 | bbd477b940c2aaf1633294cba9c3454d | 9B784D2E5E6DB4EC627039113EB1C12B | Kekkyoku Nankyoku Daibouken (J) (REV0) [b1][o1].nes
7 | NES | 4094 | Antarctic Adventure | F01CE625CFCE3596D4A9D13EF9F17352 | 1694 | 0E4000F6AC31AEFA5BBC42C37AE2895B | f01ce625cfce3596d4a9d13ef9f17352 | F7E6238C4AF74267A5900F28BE4E4E6D | Kekkyoku Nankyoku Daibouken (J) (REV0) [T+Rus_Guyver].nes
7 | NES | 1542 | Anticipation | 14DE068A0EA0B211C697D8795228C282 | 5347 | REMOVE. V15 present | &nbsp; | &nbsp; | &nbsp;
7 | NES | 1542 | Anticipation | 608692C80BE6F94753C06566EDB5636D | 5347 | 2BC3845C6F70DD96D1B0CFD35532456A | 608692c80be6f94753c06566edb5636d | 9DCC5C936ABDEEE9D768C6E45870A32A | Anticipation (U) [b3].nes
7 | NES | 1542 | Anticipation | E6F6A99AC2AC889B9D70C0EABF52AF69 | 5347 | REMOVE. V15 present | &nbsp; | &nbsp; | &nbsp;
7 | NES | 1553 | Bad Dudes | F2A3F31DA718A26747CF487A6D80A6F1 | 631 | E6AA81E046BEC9308392A4F0560980DD | f2a3f31da718a26747cf487a6d80a6f1 | 395EE29DC784A7E8336E00BA378AEF7D | Dragon Ninja (J) (PRG0) [T-Eng_Stardust Crusaders].nes
7 | NES | 1556 | Balloon Fight | 6A1007C559B71EABFE23950265E59849 | 314 | E5F0C9FC74CECEBE711AFB8A964FC094 | 6a1007c559b71eabfe23950265e59849 | CCF23221C01CEE1A5C59350E10B10CB2 | Balloon Fight (E) [T+Fre1.1_ks151].nes
7 | NES | 5795 | Banana Prince | 6691B94FAAAE34DC97E42DBAFBA3A26C | 2011 | 6405B801A645AB6F96E9EC2AD1DFF4A8 | 6691b94faaae34dc97e42dbafba3a26c | B2394B6C568BAC8C26015DB9C0D25068 | Banana Prince (G) [T+Rus1.25F_ViZed].nes
7 | NES | 1569 | Batman Returns | E3B1693B97EDF2336722451C250B0792 | 2406 | B12FEBFE016C48DD16ED68BC7BEDEA53 | e3b1693b97edf2336722451c250b0792 | EF190D4598455E793E7C7A9433E1518E | Batman Returns (U) [T+Bra_Tradu-GameX].nes
7 | NES | 4559 | Batman: Return of the Joker | BE5FE6F0842FA38DFA760BA56B7E28CD | 1522 | 7725E9F732302CAA53D25E978AECCEAB | be5fe6f0842fa38dfa760ba56b7e28cd | 715BFAE31C1288B6372DBE16635B3384 | Batman - Return of the Joker (U) [T+Rus_pscd.ru].nes
7 | NES | 4808 | Binary Land | 79D9EB5E940F130E092682A517DC9D2B | 1198 | 7C396ED62943CF875880ADA9F13523DF | 79d9eb5e940f130e092682a517dc9d2b | 97BD3DE54B1B6F8EB2E2F98DC4B80790 | Binary Land (J) [T+Rus1.0_BHLady].nes
7 | NES | 1590 | Boy and His Blob, A: Trouble on Blobolonia | CE1BF3B6B850874C076FC44FCF730890 | 5118 | 0D4C597F5FB6BC4C1726B83DBCE26C15 | ce1bf3b6b850874c076fc44fcf730890 | D61F2D4D02A47CBF422E5F6E4F8638E3 | Boy and His Blob, A - Trouble on Blobolonia (U) [T+Spa99%_Emu4ever].nes
7 | NES | 2360 | Bucky O'Hare | 9ABB2039F428714B2B93B019BDEED7BF | 968 | 715bfae31c1288b6372dbe16635b3384 | 9abb2039f428714b2b93b019bdeed7bf | F3CCC1E711EE7BD538153F50D144A09D | Bucky O'Hare (U) [T+Pol].nes
7 | NES | 1597 | Bugs Bunny Crazy Castle, The | 6A6763329F9E62495AD34A05270AEE7B | 2524 | REMOVE. V15 present | &nbsp; | &nbsp; | &nbsp;

**Comment by meleu** [comment]
This isn't the best repo to report this kind of thing.

I suggest moving this to [RAPatches](https://github.com/RetroAchievements/RAPatches/issues).

TBH there isn't a specific repository to handle hash inconsistencies, but RAPatches seems to be the closest one to this kind of issue (and @televandalist could take a look at it). Also, it would keep this issue tracker here dedicated to RALibretro-specific problems.
