### ISSUE TITLE
[Feature Request] allow multiple discs names to be named as cdX where X is a number

### ISSUE THREAD

**Issue by PIC16f841** [RetroAchievements/RALibretro#297]
Some frontends like emulation station display chd (or bin) files as games so the solution has been to rename the files to be cd1, cd2, etc so only the m3u file is listed then.
Unfortunately doing this this ruins retroachievements as only CHD or BIN files seems to be supported.
Would it be possible to add the ability to read these files?

**Comment by Sanaki** [comment]
I'm not a fan of breaking standards and creating problems just to work around someone else's poor design.

**Comment by Jamiras** [comment]
The achievement identification code largely relies on the file extension to determine which hashing algorithm to apply. If the extension isn't recognized the entire file (up to the first 64MB) will be hashed.

**Comment by PIC16f841** [comment]
This is the recommended approach for storing multiple disc by retropie fellas as per https://retropie.org.uk/docs/Playstation-1/
I think recalbox also uses the same "hack" to circumvent the issue

What if there was a name convention like "<game name>.chd.cd1, <game name>.chd.cd2 and so forth? This way you could tell if the game is a chd or a bin looking for the prefix...

Another option could be to rely on magic numbers/file header to identify the CHD instead of trusting the file extension. There are a limited number of file formats supported anyway for each emulator so it shouldn't be overkilling....
Can't you just simply acknowledge that whatever is listed on the m3u is a "disk file", disregarding on the file extension and then apply the magic numbers approach?

**Comment by Jamiras** [comment]
m3u files aren't just for CD-ROM/DVDs. PC-88 is known to use it for multiple floppy disk games. We wouldn't want to try to use CD-ROM hashing algorithms on floppy disks.

Using a multi-part extension isn't a great solution as the extension is still "cd1", and the second period is assumed to be part of the game title. We'd still need a case to match "cd1" to check for the secondary extension.

As long as the extensions are standardized (i.e. "cd#"), I guess it could be reasonable to support them using the same logic as the "chd" extension.

**Comment by Jamiras** [comment]
There's still the potential problem of deciding if the "cd#" file is a "cue", "chd", "iso", "gdi", or "bin" file.

**Comment by Sanaki** [comment]
Most cores also don't support this naming scheme, by the way. It's come up a few times where people want it standardized instead of fixing the root problem in the frontends using this approach.

**Comment by Jamiras** [comment]
Would putting the chd files in a subdirectory prevent the frontend from processing them? m3u's support both relative and full paths.

**Comment by PIC16f841** [comment]
> Would putting the chd files in a subdirectory prevent the frontend from processing them? m3u's support both relative and full paths.

That worked, thanks
