### ISSUE TITLE
Document missing dependencies

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#31]
When compiling on Windows with all submodules initialized, there are still missing dependencies that require manually moving libraries to the build directory in order to debug. These include `SDL2.dll` and libretro cores.

If SDL2 can be built from the submodule version, then this should be automated when compiling RALibretro. Otherwise, the submodule should be removed. As for libretro dependencies, the supported/required cores should be listed and a download link (e.g. to the nightly builds) provided. In the future it would be ideal to add them as submodules and integrate them into the build process as well.

**Comment by leiradel** [comment]
The SDL2 submodule is there only for the header files, and it's not my intention to build it along with RALibretro. I agree we need to document what is needed to properly debug RALibretro though.

The `dl-cores.sh` script, which must be run from the repository root folder, will download the supported cores into the `bin/Cores` folder. I also don't see value in downloading cores as part of the build process, this should also be explained somewhere.

**Comment by rzumer** [comment]
I didn't notice the download script there. A separate script to handle dependencies sounds fine, though I personally prefer including that in the build process, only downloading files if they are not present.

**Comment by meleu** [comment]
compiling the cores can possibly add more stuff to handle, their dependencies, etc...
That's why we chose to download the ones built by the [libretro's buildbot](https://buildbot.libretro.com/).

**Comment by rzumer** [comment]
Closed by #37 as far as I can tell, though more detail could be useful.
