### ISSUE TITLE
ASCII Text memory search is not functional if there's only one search result

### ISSUE THREAD

**Issue by suXinjke** [RetroAchievements/RALibretro#311]
If I do a new ASCII search and filter by constant text, if there's only one result entry - it doesn't show anything but can be clicked (it leads you to 0x0). If there are multiple results after filtering, everything is displayed properly.

![not ok](https://user-images.githubusercontent.com/9765719/144391151-9459aca1-9ec7-4f63-8c4f-ab71b9c67a2a.png)

![ok](https://user-images.githubusercontent.com/9765719/144391145-a32d3e00-6fc1-4401-90bc-8515e0aaec21.png)

Issuing this on
- RALibretro 1.3.8
- Windows 10 x64 21H1

**Comment by Jamiras** [comment]
Issues related to the tool windows belong in the RAIntegration repository. This particular one has been fixed, but not released.

https://github.com/RetroAchievements/RAIntegration/pull/809
