### ISSUE TITLE
xxxx-Rich.txt dropdown

### ISSUE THREAD

**Issue by snowpin** [RetroAchievements/RALibretro#319]
Curious if we can get an option to load the RP file for loaded game in notepad directly from the dropdown menu with the other dev tools?

![Untitled](https://user-images.githubusercontent.com/6635720/149173888-a630328a-b834-4f59-a64e-caaea8ef808f.png)

**Comment by Jamiras** [comment]
The first time you posted this (#318), I moved to the RAIntegration repository (https://github.com/RetroAchievements/RAIntegration/issues/856). This is a toolkit request, not a ralibretro request. it affects all emulators that use the DLL.

**Comment by snowpin** [comment]
My bad. Didn't see the last one moved as it didn't send me emails so i figured while my net was being slow it didn't post.
