### ISSUE TITLE
Button Pressing & Mappings are broken on Dreamcast (Flycast?)

### ISSUE THREAD

**Issue by Apocalypse612** [RetroAchievements/RALibretro#327]
Tested on "Power Stone 2 v1.000 (2000)(EIDOS)(PAL)"

I've tested several controllers and they have the same problems. Several issues, including:
1) Instant turbo on (both?) of my trigger buttons. Additionally, I can't get single pressing to work with them. I think it might be triggering the pressure-sensitive setting before the button press can happen.
2) Buttons aren't doing what they're supposed to be doing. I can't even explain wtf is going on here because I have no idea.

I cannot duplicate the proper button mappings between RA-Stable (working!), and RALibretro (broken). Aside from the triggers, the other buttons aren't doing what they're supposed to be doing, either. 

Additionally, there's a lack of Dreamcast joypad button mapping documentation on RALibretro documentation official page. However, I tried it with keyboard mappings just to test - and the issues persisted.

**Comment by Apocalypse612** [comment]
Okay, figured it out thanks to KickMeElmo. Behavior is normal once coresetting for Flycast has digital triggers enabled. This should prob be the default. It breaks controls horribly otherwise.

**Comment by Sanaki** [comment]
It's a core option. The default is specified by the core.

**Comment by nexus382** [comment]
this is shit thou, because when i use digital triggers, it makes it so they are no longer prssure sensitivvfe, and go from 0% to 100% and back... when off, it seems that both triggers are always like 75% deperessed ( in racing games im doing brakeStands, gass and brake at once) and turning digital on means no pressure sensitive values (anything not 0 or 100)

**Comment by Jamiras** [comment]
Closing this in favor of #407, which is a more concise feature request instead of a bug report.
