### ISSUE TITLE
FDS file loading silently fails when a system is absent

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#33]
FCEUmm expects a `disksys.rom` system to be present in the Systems directory. If this is not the case, it will return an error, which RALibretro will silently dispose of. The application will enter an error state where another attempt at loading a file or closing the application will cause memory errors to occur. This will be a common issue if #32 is pulled and integrated in an upcoming release.

**Comment by leiradel** [comment]
FCEUmm correctly returns `false` in `retro_load_game` if that file cannot be found, and RALibretro will check for this in `Application::loadGame()`. Unless there's some issue in the FSM that controls the application state, everything should work.

I'll try to replicate the issue.

**Comment by rzumer** [comment]
Right, ultimately it seems that this `false` return value is sent back up through the chain, resulting in the load process being aborted without feedback or recovery measures being taken.

It would be nice to get error details from the core in order to produce accurate messages and degrade gracefully, but I don't know if that is possible.
