### ISSUE TITLE
[Feature Request] Accessibility in the Memory Inspector

### ISSUE THREAD

**Issue by devin-hart** [RetroAchievements/RALibretro#347]
![image](https://user-images.githubusercontent.com/32463419/198645323-85cf126b-7985-4b26-8cb0-d241ea58c132.png)

### Issue:
As a color blind user it's very hard to discern a selected memory address from an unselected memory address. There isn't enough contrast between the red color on the white background versus the black color on the white background.

### Potential Solutions (in order of best practice):
- Dark mode. Changing the background to a dark gray, with white unselected addresses and red selected addresses would help tremendously. All those white windows are so bright!

![Untitled](https://user-images.githubusercontent.com/32463419/198660784-7b6ff518-3350-425b-ae81-e99fd5a0d8c4.png)

- Background color on the selected memory address. If a dark mode is not an option hopefully adding a background color to the selected address could be implemented.

![highlight](https://user-images.githubusercontent.com/32463419/198665268-3712e5ff-ccac-449f-ae4e-12e6a2ac769e.png)

Hopefully, this wouldn't be extremely difficult to implement and both myself and my eyes will be eternally grateful.

**Comment by Maximdraco** [comment]
I like the idea of a Dark Theme, I'm not colorblind, I simply like it

**Comment by Jamiras** [comment]
First, this is not a RALibretro issue. You should have clicked on the "Suggest a new toolkit feature" button. Anything opened from the "RetroAchievements" menu is part of the toolkit, and affects all the standalone emulators, not just RALibretro.

Secondly, you can already modify the colors used in the memory inspector by putting an `editor-theme.json` file in your overlay directory (or if one already exists, just editing it). The default (**and a dark theme**) versions are [here](https://github.com/RetroAchievements/RAIntegration/tree/master/data) (you'll need to rename the dark theme one). Note that this only affects the memory view, as that's rendered by the toolkit. The rest of the application uses whatever colors are provided by Windows itself. You can see an example of the dark themed memory viewer in a window using the standard Windows theme in the PR that introduced the functionality: https://github.com/RetroAchievements/RAIntegration/pull/561

**Comment by devin-hart** [comment]
> First, this is not a RALibretro issue. You should have clicked on the "Suggest a new toolkit feature" button. Anything opened from the "RetroAchievements" menu is part of the toolkit, and affects all the standalone emulators, not just RALibretro.
> 
> Secondly, you can already modify the colors used in the memory inspector by putting an `editor-theme.json` file in your overlay directory (or if one already exists, just editing it). The default (**and a dark theme**) versions are [here](https://github.com/RetroAchievements/RAIntegration/tree/master/data) (you'll need to rename the dark theme one). Note that this only affects the memory view, as that's rendered by the toolkit. The rest of the application uses whatever colors are provided by Windows itself. You can see an example of the dark themed memory viewer in a window using the standard Windows theme in the PR that introduced the functionality: [RetroAchievements/RAIntegration#561](https://github.com/RetroAchievements/RAIntegration/pull/561)

My apologies for the incorrect filing of this issue.

This is great news! Thanks for answering. Considering this closed.
