### ISSUE TITLE
AVGN Doom VIDEO

### ISSUE THREAD

**Issue by SomeonePissed** [RetroAchievements/RALibretro#348]
It is about retroachievements,didnt you find strange that he asked your credit card info for you to see it?And you now pretty damn well that he never censores his videos.

You are all in very BIG TROUBLE

**Comment by Sanaki** [comment]
I have no idea what you're talking about, but it's certainly both off-topic and irrelevant.

**Comment by SomeonePissed** [comment]
Don't play coi with me you know pretty well
