### ISSUE TITLE
RALibretro close itself after reseting the list of codenotes after deleting one

### ISSUE THREAD

**Issue by Maximdraco** [RetroAchievements/RALibretro#352]
**Describe the bug**
Once I deleted a codenote and press reset to update the list of codenotes, the emulator close itself. At least with the Genesis Plus GX (v1.7.4) Core.

**To Reproduce**
1. Use RALibretro 1.4
2. Open a game with the Genesis Plus GX (v1.7.4) Core.
3. Create and publish a Codenote.
4. Open list of codenotes.
5. Delete the Codenote and update the list.

**Comment by Jamiras** [comment]
This is most likely due to https://github.com/RetroAchievements/RAIntegration/pull/943, which has been fixed, but not released. I was unable to reproduce on either the latest version (containing the fix) or the official 1.1.0 DLL.
