### ISSUE TITLE
Extend filetype support for PPSSPP

### ISSUE THREAD

**Issue by Coloradohusky** [RetroAchievements/RALibretro#373]
[According to the LibRetro docs](https://docs.libretro.com/library/ppsspp/#extensions), the PPSSPP core supports elf, cso, prx, and pbp files, as well as iso files which are already supported by RetroAchievements. I'd like support for those other four filetypes, for better homebrew support.
Currently, loading the game appears to work, after clicking OK to the `Could not open track` error popup:
![image](https://user-images.githubusercontent.com/45430066/233807016-e5f363c1-2d02-4e26-9b4b-03f85e6b6d83.png)
![image](https://user-images.githubusercontent.com/45430066/233807038-8163967f-20ad-4b35-b04e-df4b66e3d897.png)
![image](https://user-images.githubusercontent.com/45430066/233807081-fd0e70a9-3471-46cd-bbb5-5883da8b3a91.png)
The memory inspector also appears to work fine, being able to find the values I need - for example, in the 2048 homebrew, I can successfully find the score and high score addresses.
This will also need updating on rcheevos as well, to update how these files are handled there (instead of just saying that they couldn't open the track).

**Comment by Jamiras** [comment]
This is because the code that generates the hash doesn't understand those file types. They won't work in RetroArch either.

**Comment by Coloradohusky** [comment]
Just found https://retroachievements.org/viewtopic.php?t=14341&c=99331#99331, that'll work
