### ISSUE TITLE
theres stuttering in NES games

### ISSUE THREAD

**Issue by ExGuestCJ** [RetroAchievements/RALibretro#388]
**Expected behavior**
The game playing normally

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Comment by Jamiras** [comment]
No. There's not.

**Comment by ExGuestCJ** [comment]
probably its my pc

**Comment by ExGuestCJ** [comment]
or probably isnt since the standalone version of mesen runs perfectly
