### ISSUE TITLE
Add support for compressed ROMs

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#4]
_From @leiradel on March 1, 2018 12:49_

_Copied from original issue: meleu/RALibretro#22_

**Comment by Jamiras** [comment]
Implemented by #4.

Relies on the core's `info->need_fullpath` parameter. If that is false, we can unzip the file and load it directly into the core. If it's true, we have to let the core tell us which files it supports. The "Open Game" dialog will include 'zip' in the "Supported Files" selection if the core supports the functionality.

**NOTE: if a zip file contains more than one file or any sort of directory structure, it will not load. The zip processing logic is very simple.**

The following cores now support zip files:
* FCEUmm
* Gambatte
* Mednafen VB
* mGBA
* Snes9x
* Stella
* ProSystem

The following cores still do not support zip files:
* Beetle SGX
* Genesis Plus GX
* Handy
* Mednafen NGP
* PicoDrive

Additionally, FBA requires a zip file, but does not unzip it.
