### ISSUE TITLE
Xenia support?

### ISSUE THREAD

**Issue by Koriebonx98** [RetroAchievements/RALibretro#400]
**Is your feature request related to a problem? Please describe.**

with all these emulators supporting RA it would be good to inc modern emulators, idealy I know it’s not completely possible.

however xenia canary build supports achievements, is there away to use that to record the achievements for Xbox 360? if yes then this would be a good way to have support for Xenia.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jamiras** [comment]
This is not the appropriate place for that request. This repository is for issues/enhancements for the RAlibretro frontend for libretro cores. If you want RetroAchievements integrated into the Xenia emulator, post an issue on the Xenia github - there might even already be one.
