### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by MedoSM64** [RetroAchievements/RALibretro#403]
When I enter the core, e.g. N64 (Parallel 64), I don't know how to find the graphics settings of the Paraller 64 core. Can you help me?

**Comment by Jamiras** [comment]
Which button did you press to get here? `Bug` or `Feature`? Clearly this is neither of those.

Core-related settings can be accessed from the "Core Settings" option under the "Settings" menu. (I'm not sure how to make that any more obvious). 
![image](https://github.com/RetroAchievements/RALibretro/assets/32680403/3df01491-160a-44c9-aa3f-31d8dae977a2)

That will open a window for settings for the currently selected core (sometimes you need to have a game loaded to see all of the settings).

ParaLLEl doesn't implement setting groups, so all the settings (including the graphics ones) will appear at the same time.
