### ISSUE TITLE
analog trigger issue on RAlibretro (JR DEV here)

### ISSUE THREAD

**Issue by nexus382** [RetroAchievements/RALibretro#407]
**Describe the bug**/**To Reproduce**
I am a Dev on RA, making Cheevos for dreamcast, annd the analog triggers are not being picked up by the front end is my best guess.  
Using my ps4 controller that i use with EVERYTHING, including retro arch using the same FC core, and FC standalone, When playing some racing games, The triggers BOTH seem to be Depressed  ( If you load up Daytona usa 2001 for dreamcast, go to options on main menu, then to controller config, and to the calabration mode, that is the PERFECT graphical representation of what is going on.... This screen is for doing things like limiting the range/deadzones of the L, and R triggers and the stick for stearing. you set them by pressing the buttons JUST as hard as you want, and then hit "A"" to lock your value... if you do this you should see both triggers pressed about 75%... and if you go to core settings and ENABLE DIGITAL TRIGGERS, then your tiggers work, but only 0% or 100%. not pressure sensitive any more, adn its on or offf.... nothing in between.. 

**Expected behavior**
triggers on the dreamcast are analog, and once talking with the Flycast dev, flyinghead, he said that "iirc digital triggers was for old versions of the frontend/retroarch that doesn't support analog triiggers".... but retroarch supports analog triggers... and i find it very shocking RAlibretro wouldnt....

**Desktop (please complete the following information):**
 - OS: win 11

**Smartphone (please complete the following information):**

**Additional context**
I know this seems silly and trivial..... but when im mining and need to play the game a bit to unlock shit and what not, playing many games with 0/100% on your triggers, makes things VERY hard.

**Comment by JomSpoons** [comment]
Also having trouble regarding triggers in Dreamcast games. Was trying to play Crazy Taxi and the triggers were not getting picked up at all, even when mapped to non-analog inputs like bumpers.

**Comment by JomSpoons** [comment]
I would also really like to see analog triggers properly implemented, as I'm not a fan of RetroArch's UI and would much rather use RALibretro as my frontend.
