### ISSUE TITLE
Dreamcast core not visible in version 1.7.1

### ISSUE THREAD

**Issue by Anoticx** [RetroAchievements/RALibretro#410]
When i wanted to play a Dreamcast game and I wanted to load up the Dreamcast core, it wasn't there. I don't know what happened. i didn't know why it suddenly disappeared because it there visible in version 1.7.0, but i can't download the 1.7.0 version

**Comment by Jamiras** [comment]
You probably downloaded the 32-bit version. Flycast only runs in the 64-bit version of RALibretro.
