### ISSUE TITLE
Leaderboards always enabled whether I disable them or not

### ISSUE THREAD

**Issue by JamMasterJay1** [RetroAchievements/RALibretro#411]
**Describe the bug**
Every time I start up a game in RALibRetro (if the game has a leaderboard attached on RetroAchievements) I get several popups telling me the leaderboard run has started despite the fact I have disabled leaderboards. This has been happening since 1.7 was introduced I believe. I am now on 1.7.1 and it's still happening.

**To Reproduce**
1. Start game linked to RetroAchievements that has a leaderboard attached to it.
2. A notification will appear, sometimes several, to tell me my leaderboard run has started despite 'Enable Leaderboards' being disabled.

**Expected behavior**
There should be no notification to tell me leaderboard has been enabled. It also shouldn't submit leaderboard information to RetroAchievements website but it appears it is uploading all my times.

**Screenshots**
[https://ibb.co/0s5932J](url)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by wescopeland** [comment]
Leaderboards are not optional when hardcore mode is enabled. I'm not sure if there should perhaps be a UX change in RALibretro to better indicate this.

**Comment by Jamiras** [comment]
It's a bug in the 1.3.0 DLL. Fix is pending: https://github.com/RetroAchievements/RAIntegration/pull/1102
