### ISSUE TITLE
RALibretro crashes after loading inconsistent Rich Presence

### ISSUE THREAD

**Issue by xTr4ceur** [RetroAchievements/RALibretro#418]
I've wrote an inconsistent rich presence which used 2 times the same value in a Lookup variable
Instead of a parse error code the program crashed and i dont weren able to open it again
Needed to empty my RA-Cache folder to find the issue, because other files worked and i tought my pc gotten corrupted.

I started to write a new rp for https://retroachievements.org/game/754
and here is code that's produce the crash:

> Lookup:StageID
> 0x901-0x908=explores the island of the thieves  `0x908 is the double used value`
> 0x908,0x909,0x911=explores the Lighthouse
> Display:
> test

1. put my code snippet into an "754-Rich.txt"
2. save it and put it into your RA-Cache Folder
3. Start the game and it will instantly crash

Never had this issue before, I got everytime an "parse error" code line instead of a crash.
It was the 1st time that it happens in this specific case.

**Comment by xTr4ceur** [comment]
> 0x908,0x909,0x911=explores the Lighthouse
> 0x901-0x908=explores the island of the thieves

This order produce only a parse error instead of a crash. But if im swap the order again like I did in my 1st post, it crashes instantly again.

**Comment by Jamiras** [comment]
In the problematic scenario, 0x908 is marked as a duplicate, but then 0x909 and 0x911 are valid, so the duplicate error gets forgotten. This results in an invalid entry in the lookup, and when the rich presence is processed, that causes the crash.

This isn't specifically a RALibretro error, anything that consumes the faulty script would encouter the same error.
