### ISSUE TITLE
Emulation settings: screen rotation 

### ISSUE THREAD

**Issue by salvadorc17** [RetroAchievements/RALibretro#48]
This option is missing for the Atari 7800 and Arcade emulators, to allow run some games properly.
![screenrotation](https://user-images.githubusercontent.com/13541889/47261948-fe87c780-d49f-11e8-86db-5e041614fb5d.png)

**Comment by televandalist** [comment]
That'll make arcade cheevos explode probably. They're usually sideways, but I found one that's actually upside-down (http://retroachievements.org/Game/13381)
