### ISSUE TITLE
Bazooka Blitzkrieg SNES crashes Emulator

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RALibretro#5]
_From @grenade44 on March 21, 2018 22:39_

Tried playing Bazooka Blitzkrieg and it crashes the emulator.

_Copied from original issue: meleu/RALibretro#37_

**Comment by leiradel** [comment]
Is this an issue? Does the game work in RetroArch?

**Comment by meleu** [comment]
hey, I've just launched the game in 1.0.6 and it runs pretty fine.

@grenade44 could you test it again using the most uptodate version? You can found it here: http://docs.retroachievements.org/Downloads/

**Comment by grenade44** [comment]
@meleu been very busy recently, if I’m on the computer later I will test with the latest emu. Otherwise it will be tomorrow.

**Comment by grenade44** [comment]
@meleu just tested and the game now loads fine but cant get any of the controls to work. which controller settings do I need to use for lighting gun??
