### ISSUE TITLE
Make RALib Single Input by Default

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RALibretro#51]
Requesting that Port 1 is the only active port by default.

I often need to change multiple ports to none and/or unassigned every time a core (and sometimes a game) is loaded. I only have one XInput Controller, but RALib initially wants that one controller to control several ports.

Normally it wouldn't be that big of a deal, but I have noticed that FB Alpha and PC Engine CD games don't agree with this at all and will often hang or crash RALib if an input setting is adjusted. This is especially frustrating since changing games for these cores require RALib to be shut down and restarted every time a game is switched.

**Comment by televandalist** [comment]
Also, some single player games with "second controller cheat codes" have cheat protection that monitors P2 input, and can be mistakenly triggered due to the current default settings.

**Comment by Jamiras** [comment]
Is this still an issue? Input 2 has separate bindings, which default to not being set.

**Comment by televandalist** [comment]
Nah. This is back when RALib input settings were really, really bad.

**Comment by televandalist** [comment]
Ī
