### ISSUE TITLE
fds eject and swap sides input seemingly isnt bound to the keyboard or at least not to the default retroarch inputs

### ISSUE THREAD

**Issue by kcin2001** [RetroAchievements/RALibretro#54]
this makes fds games impossible to dev for

**Comment by meleu** [comment]
leiradel seems to be a bit busy lately, let's ping @rzumer and see if he can lend a hand (as he seems to be interested in fds stuff).

**Comment by rzumer** [comment]
C inserts/ejects and D swaps sides while ejected (tested with current master).

**Comment by meleu** [comment]
could you also, please, update the wiki accordingly?
https://github.com/RetroAchievements/docs/wiki/RALibretro

I can generate the doc pages later

**Comment by rzumer** [comment]
Done.
