### ISSUE TITLE
Lynx BIOS freezes on load

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RALibretro#59]
The whole application stops responding when loading Lynx titles using the Handy core, while a BIOS file is present in the `System` directory. The file is named according to the `libretro` documentation for Handy (https://docs.libretro.com/library/handy/) and the MD5 hash used for my tests matches. When the file is absent, loading works as expected (because Handy provides a pseudo BIOS to load without a real one present).

**Comment by Jamiras** [comment]
I was able to load Chip's Challenge and Shanghai using the latest Handy core with the BIOS file present. Assuming this has been fixed somewhere in the last five years.
