### ISSUE TITLE
could the vbam core be added to the core list?

### ISSUE THREAD

**Issue by kcin2001** [RetroAchievements/RALibretro#60]
i would like to be able to dev for a pokemon hack that doesnt work in mgba and i want to be able to use 1 save file between retroarch and an ra compatible dev emu

**Comment by leiradel** [comment]
VBA-M supports achievements so it shouldn't be hard to add it to RALibretro.

**Comment by kcin2001** [comment]
Im sure its just as simple as adding it to a list, i just dont know where that list is or how to compile things to test
