### ISSUE TITLE
FBA reset the game with fast forward

### ISSUE THREAD

**Issue by Kouga1994** [RetroAchievements/RALibretro#63]
When I choose some game of FBA or neogeo, it works with fast forward but without advancing, the game resets when it arrives at the logo qsound and neogeo.

**Comment by leiradel** [comment]
Can you please write the exact steps needed to reproduce the issue? Thanks.

**Comment by Kouga1994** [comment]
I'm using RALibretro, the multi emulator, choosing Core FBA, when I start any Cps I, II, III or NEO GEO game, it works. but when the opening of the Qsound and Neo Geo logo arrives, the game is restarted and again when it arrives at the logo.
but when I press the fast forward button, it works, but it stays fast. this problem happens with some Cps and neo geo games. What can I do ?

**Comment by meleu** [comment]
I confirm the annoying restart loop behavior (but never noticed we could pass it with fast-forward).

**Comment by Jamiras** [comment]
FBA is deprecated, and I do not see this behavior in FBNeo.
