### ISSUE TITLE
FBA Works with fast forward

### ISSUE THREAD

**Issue by Kouga1994** [RetroAchievements/RALibretro#64]
I'm using RALibretro, the multi emulator, choosing Core FBA, when I start any Cps I, II, III or NEO GEO game, it works. but when the opening of the Qsound and Neo Geo logo arrives, the game is restarted and again when it arrives at the logo.
but when I press the fast forward button, it works, but it stays fast. this problem happens with some Cps and neo geo games. What can I do ?

**Comment by meleu** [comment]
I confirm the annoying restart loop behavior (but never noticed we could pass it with fast-forward).

**Comment by meleu** [comment]
Uh? :thinking: 

I realized that this is a duplicated entry. Your issue is being treated in #63.

I'm closing this one.
