### ISSUE TITLE
Start a Core and ROM via command line parameters

### ISSUE THREAD

**Issue by theMK2k** [RetroAchievements/RALibretro#66]
Hi,

is there a possibility to start RALibretro with a core and a given ROM file as command line parameter?

**Comment by Sanaki** [comment]
This could have the secondary benefit of allowing subsystems to be specified, which currently isn't possible in RALib.

**Comment by theMK2k** [comment]
I created a PR which introduces parsing of command line arguments and (trying) to load a game with core and system: https://github.com/RetroAchievements/RALibretro/pull/342
