### ISSUE TITLE
ProSystem core not with current download

### ISSUE THREAD

**Issue by televandalist** [RetroAchievements/RALibretro#68]
The Atari 7800 core shows up in the core folder as prosystem_libretro.dll.zip and it is a 0 byte file that is neither a zip nor a dll.

**Comment by meleu** [comment]
whoops! my bad. I think I forgot to pack the prosystem core when I created the new pack. I'll make a new zip and upload it to the server tonight.

In the mean time, you can get it here directly from the libretro server: https://buildbot.libretro.com/nightly/windows/x86/latest/prosystem_libretro.dll.zip

Just unzip and put the file in the `Cores` folder.

**Comment by meleu** [comment]
I've just uploaded a new zip. Could you download it and check?

Feel free to reopen the issue if the problem persists.

**Comment by televandalist** [comment]
It's in there and it works. Thanks.
