### ISSUE TITLE
Cores outdated and not best compatible

### ISSUE THREAD

**Issue by salvadorc17** [RetroAchievements/RALibretro#74]
The cores added via download link are not best compatible and seems outdated, arcade one does not have full game list support (Cps2/3)

**Comment by leiradel** [comment]
Maybe it's time to update the cores bundled with RALibretro.

@Jamiras @meleu thoughts?

**Comment by Jamiras** [comment]
I don't think we should bundle the cores with RALibRetro or include them in the repository. See also #38. As discussed there every binary every included in the repository is downloaded every time someone clones the repository, so we have to be very picky when deciding which binaries to update and when.

I think we should host the approved cores on the server, along with a single configuration file that lists all the supported cores and their current sizes. We could read that on every login (similar to how we validate the emulator version) and if there's a mismatch (or missing core), have RALibRetro download them then. 

This would also address #38 in a way that didn't "make developers run a script before start working with it".

**Comment by salvadorc17** [comment]
Could you allow me to share fba arcade updated core, so we can allow support for more system.

**Comment by leiradel** [comment]
`RALibretro.zip` includes the cores, it's just a matter of updating the cores before creating the zip, no need to include them in the repo.

**Comment by salvadorc17** [comment]
Yes that true, still the version added dont have latest cores updated, and need to be checked. Also fba core need to be adapted so can work with extra system.

**Comment by Jamiras** [comment]
Users are now able to download/update their cores from within the application (#103). There's no reason to explicitly include any version with the distribution.
