### ISSUE TITLE
Bring all cores that support achievements in Retroarch into RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#75]
As pointed out by many achievement developers, often bringing much frustration, we are unable to debug what could be core specific issues due to lack of available cores.

I would say this is an essential need as we want to continue to adequately support Retroarch.

**Comment by kdecks** [comment]
closed after discussion with leiradel

**Comment by leiradel** [comment]
I don't think it should be closed, or maybe one issue per missing core should be opened. I'd say that the goal is desirable, it's just that it's not simple to add new cores to RALibretro, each core must be added according to the way it exposes its memory to the outside world.

**Comment by kdecks** [comment]
I will add the one issue per missing core.

**Comment by kdecks** [comment]
After listing all the supported cores as issues I second guess how valuable this effort would be...

It definitely would be helpful in certain cases, and would help for debugging and isolating unique core-related issues. Probably best to focus on most-used and/or consoles that that have no RALib support at all like Muppen64.
