### ISSUE TITLE
Add Mesen core (NES) to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#77]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
I'm suspicious that this core is actually supported. When loaded in RALibRetro, the entire memory space is just 0s.

**Comment by televandalist** [comment]
I'd wait until how it handles SRAM is fixed. Euclide opened an issue with Mesen for it a while back and used one of my examples.

**Comment by kdecks** [comment]
Is there a for us to get "supported" to get their support removed?

**Comment by soredake** [comment]
Any progress on this?

**Comment by meleu** [comment]
nops, the problem still happens

**Comment by Jamiras** [comment]
Mesen was added to 1.3.3 via #218
