### ISSUE TITLE
Add Quicknes core (NES) to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#78]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
I'm suspicious that this core is actually supported. When loaded in RALibRetro, the entire memory space is just 0s.

**Comment by kdecks** [comment]
I've personally successfully earned achievements with FCEUmm, Mesen and QuickNes. But often one core won't work for a certain set (or it won't emulate properly), so I'd just cycle to the next one.
