### ISSUE TITLE
Add Snes9x 2010 core to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#79]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
https://forums.libretro.com/t/snes-cores-so-numerous-similar-and-confusing-names/9904/3

> Snes9x with no date is the up-to-date mainline core that has upstream integration (i.e., the “official” snes9x). The date-stamped forks are snapshots from the year their code is based on. Snes9x has gotten slower over time as its accuracy has improved, such that many of the weaker platforms we support can’t run mainline at full speed, so we have older forks that provide more favorable performance thresholds at the cost of accuracy.

As such, I don't believe there's any reason to support the date-stamped Snes9x cores. If one is required for testing something, it's easy enough to edit the local cores.json file.
