### ISSUE TITLE
Add bsnes cores to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#81]
These are missing cores with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

- bsnes Accuracy
- bsnes Balanced
- bsnes Performance
- bsnes-mercury Accuracy
- bsnes-mercury Balanced
- bsnes-mercury Performance
- bsnes C++98 (v085)

Perhaps it would not be useful to add all of them.

**Comment by Jamiras** [comment]
From the descriptions provided [here](https://forums.libretro.com/t/snes-cores-so-numerous-similar-and-confusing-names/9904/2), I'm only going to add "bsnes-mercury Balanced" and "bsnes-mercury Performance".

> We would drop the mainline bsnes cores in favor of the very similar “mercury” cores except a vocal segment of bsnes users are under the erroneous impression that the mercury changes make it less accurate at default settings
