### ISSUE TITLE
Add VBA cores (GBA) to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#84]
These are missing cores with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

- VBA-M
- VBA Next

**Comment by Jamiras** [comment]
VBA-M does not currently function with the GBA memory mapping implementation for achievements in RALibRetro and crashes when loading a GBA game. It also crashes when attempting to load a zipped ROM.

**Comment by Jamiras** [comment]
VBA Next was added via #112. VBA-M will be tracked via #60
