### ISSUE TITLE
Add Muppen64Plus to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#86]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
Both this, and Mupen64PlusNext fail to load in RALibRetro:
```
[ERROR] [BCR] Error loading core: The specified module could not be found.
```

**Comment by TheVamp** [comment]
So I debugged a little bit the code and found out that the Video::supportsContext return false. This causes in Core.cpp line 723 setting the if statement every time to true. So when something is called with a hardware_context the hardware context is not set and when you try to load a Game it will crash.

If the  Video::supportsContext have `return type`, mupen64 can be loaded, but then there are more Bugs. One is that you can't switch between cores with different HardwareContext. It is possible to switch a core from a RETRO_HW_CONTEXT_NONE to a different one, but you can't switch back to RETRO_HW_CONTEXT_NONE. The Screen will keep the latest image.

My assumption is that if you switch a core with a Hardware Context it will create Errors in OpenGL. These Error States needs to be cleaned when switching to a different core. I implemented this in my local instance, but it will just allow you to switch the core one more time. So after two switches it get stuck again. 

In the Log you will see Errors like `[ERROR] [OGL] Error in Gl::clear:
[ERROR] [OGL]   INVALID_ENUM` or `
[ERROR] [OGL] Error in Gl::genTexture:
[ERROR] [OGL]   INVALID_ENUM
` these Errors seems to be caused within the GlUtil.

At the moment I am not really sure how to fix this problem, cause I am not so familiar with OpenGL and SDL.
