### ISSUE TITLE
Add ParaLLEl N64 to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#87]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
This core crashes when loading a game in RALibRetro.

**Comment by Sanaki** [comment]
Can confirm. This appears to be the only way possible to dev N64DD games, and if it can ever reasonably be fixed it would serve to allow Linux users to dev N64 as well.

**Comment by meleu** [comment]
@Sanaki have you managed to run RALibretro on Linux with a usable performance?
Last time I tried to run it through Wine (early days of RALibretro) it was laggy even for Atari 2600.

**Comment by Sanaki** [comment]
As long as I don't upscale, I get a full 60 fps on Beetle PSX. Seems fine performance-wise to me on wine 5.0 staging. That said, this conversation is better held in another more relevant location.

**Comment by meleu** [comment]
@Sanaki last post on this (off)topic: could you please share with us the steps you did to make it run?

I've just created [a page on the wiki for this](https://github.com/RetroAchievements/docs/wiki/How-to-run-RALibretro-on-Linux).

Don't worry to much about formats, I can work on it later. If you just drop some lines about your setup (which distro, etc) it would be very helpful.

Thanks in advance.
