### ISSUE TITLE
Load state while paused doesn't update screen

### ISSUE THREAD

**Issue by Jamiras** [RetroAchievements/RALibretro#9]
As a developer, I expect the screen to update when I save/load state, even while paused.

Steps:
1) Start a game (I've been using FCEUmm if this happens to be core specific)
2) Pause the emulator (;)
3) Create a save state (Shift+F1)
4) Advance a few frames (press ; until something noticably changes on the screen)
5) Load the save state (F1)

The change noted at step 4 is not reverted.

**Comment by meleu** [comment]
I confirm that. And also would like to see it "fixed".

**Comment by leiradel** [comment]
Loading a state doesn't trigger a frame, I'll need to run one frame after loading the state to have the screen updated, meaning you won't have the exact same state when you load it back from disk.

Another solution is to save the screen a different file when the state is saved, and loading it back when the corresponding state is load.

I'll go with #2, unless someone chimes in with a good reason not to.

**Comment by Jamiras** [comment]
For per-frame debugging (building achievements), not advancing the frame is critical. If not paused, you can probably skip loading the image and just let the next frame render.

**Comment by leiradel** [comment]
> If not paused, you can probably skip loading the image and just let the next frame render.

Absolutely, loading the image is just for when the game is paused.

**Comment by leiradel** [comment]
Fixed
