### ISSUE TITLE
Add Beetle PCE Fast to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#91]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
I'm not sure what "Beetle NeoPop Fast" is. The only documented NeoGeo Pocket core available is "[Beetle NeoPop](https://docs.libretro.com/library/beetle_neopop/)", which we already support. The only other core in the buildbot that looks applicable is "fbalpha2012_neogeo_libretro".

**Comment by kdecks** [comment]
I simply pulled everything from this list: https://docs.libretro.com/guides/retroachievements/

**Comment by Jamiras** [comment]
in that case, this is a duplicate of #90
