### ISSUE TITLE
Add Beetle Handy to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#92]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
This core is not recommended because it requires headered ROMs, which are apparently uncommon: https://docs.libretro.com/library/compatibility/lynx/

**Comment by kdecks** [comment]
But then would we not want to have achievement support for this core on Retroarch? Restating the point of all these issues, it's so we can better debug differences between cores.

**Comment by Sanaki** [comment]
This can likely be resolved. Headerless support was added to Beetle Lynx back in February 2019, before this issue was opened.
Commit: libretro/beetle-lynx-libretro@bd2882c
