### ISSUE TITLE
Add BlueMSX core (ColelcoVision) to RALibretro

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RALibretro#93]
This is a missing core with achievement support in an effort to bring all cores that support achievements in Retroarch into RALibretro.

**Comment by Jamiras** [comment]
Note that this core requires supplemental files:
https://docs.libretro.com/library/bluemsx/#bios

And that there are special button mappings for the difficulty dial: https://docs.libretro.com/library/bluemsx/#usage
